spring.application.name=acook-users-api
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=passwordinplaintexthaha
spring.datasource.url=jdbc:h2:file:./data/project_users
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration